"""Public API for parsing DEQ files."""

from collections.abc import Sequence
from pathlib import Path

from deq.circuit import deqagram_shim
from deq.circuit.model import (
    CodeDefinition,
    ComposeDefinition,
    Definition,
    GadgetDefinition,
    ProgramDefinition,
    DeqFile,
)

_DEFINITION_KINDS: tuple[tuple[type[Definition], str], ...] = (
    (CodeDefinition, "CODE"),
    (GadgetDefinition, "GADGET"),
    (ComposeDefinition, "COMPOSE"),
    (ProgramDefinition, "PROGRAM"),
)


def _format_definition_location(defn: Definition) -> str:
    if defn.source_file is not None and defn.source_line is not None:
        return f"{defn.source_file}:{defn.source_line}"
    if defn.source_file is not None:
        return defn.source_file
    if defn.source_line is not None:
        return f"line {defn.source_line}"
    return "<unknown location>"


def _definition_kind(defn: Definition) -> str:
    for kind_type, kind_label in _DEFINITION_KINDS:
        if isinstance(defn, kind_type):
            return kind_label
    return "definition"


def _check_no_duplicate_definition_names(definitions: list[Definition]) -> None:
    """Raise ``SyntaxError`` on the first duplicate definition name.

    Definition names share a single global namespace: a name must be
    unique across all kinds (``CODE``, ``GADGET``, ``COMPOSE``,
    ``PROGRAM``).  Iteration is in source order so the error always
    points at the first duplicate encountered.
    """
    seen: dict[str, Definition] = {}
    for defn in definitions:
        previous = seen.get(defn.name)
        if previous is not None:
            previous_kind = _definition_kind(previous)
            current_kind = _definition_kind(defn)
            if previous_kind == current_kind:
                description = f"{current_kind} {defn.name!r}"
            else:
                description = (
                    f"name {defn.name!r} (as {previous_kind} and {current_kind})"
                )
            raise SyntaxError(
                f"{description} is defined more than once: "
                f"first at {_format_definition_location(previous)}, "
                f"again at {_format_definition_location(defn)}"
            )
        seen[defn.name] = defn


def parse(text: str) -> DeqFile:
    """Parse a DEQ file string and return a :class:`DeqFile` model.

    This parses a single file's text without resolving IMPORT statements.
    Use :func:`parse_file` to parse with import resolution.

    Parsing is performed by the deqagram parser (a Rust ``pest`` parser exposed
    via PyO3) and mapped onto the :mod:`deq.circuit.model` dataclasses by
    :mod:`deq.circuit.deqagram_shim`.

    Parameters
    ----------
    text:
        The full text of a ``.deq`` file.

    Returns
    -------
    DeqFile
        The parsed semantic model.

    Raises
    ------
    SyntaxError
        If the input contains unrecoverable syntax errors.
    """
    try:
        result = deqagram_shim.parse(text)
    except ValueError as e:
        # deqagram raises ValueError on a parse error; deq's contract is
        # SyntaxError.
        raise SyntaxError(str(e)) from e

    _check_no_duplicate_definition_names(result.definitions)
    return result


def parse_file(path: str | Path) -> DeqFile:
    """Parse a DEQ file with recursive import resolution.

    IMPORT statements are resolved relative to the importing file.
    Each file is imported at most once (include-guard by absolute path).
    Definitions are tagged with their ``source_file``.

    Parameters
    ----------
    path:
        Path to the ``.deq`` file.

    Returns
    -------
    DeqFile
        A merged :class:`DeqFile` with all definitions from this file
        and its imports.

    Raises
    ------
    SyntaxError
        If any file contains syntax errors.
    FileNotFoundError
        If an imported file does not exist.
    """
    path = Path(path).resolve()
    imported: set[Path] = set()
    all_definitions: list[Definition] = []
    _resolve_file(path, imported, all_definitions)
    _check_no_duplicate_definition_names(all_definitions)
    return DeqFile(definitions=all_definitions, source_file=str(path))


def render_and_parse_file(
    path: str | Path,
    *,
    mako_defs: dict[str, str] | None = None,
    skip_mako_warning: bool = False,
) -> DeqFile:
    """Parse a DEQ file, rendering Mako templates on-the-fly if present.

    As each file in the import tree is encountered, its text is checked
    for Mako template syntax.  If any is found, the user is asked for
    confirmation (at most once), and the text is rendered through Mako
    before parsing.  This correctly handles IMPORT paths that are
    themselves generated by Mako templates.

    When no Mako syntax is detected and *mako_defs* is ``None``, each
    file is parsed directly with zero overhead.

    Parameters
    ----------
    path:
        Path to the root ``.deq`` file.
    mako_defs:
        Dict of ``key=value`` pairs passed via ``--mako``
        (e.g. ``{"d": "3", "p": "0.01"}``).  Implies *skip_mako_warning*.
    skip_mako_warning:
        Suppress the interactive safety prompt.
    """
    root = Path(path).resolve()

    # --mako implies --skip-mako-warning
    if mako_defs is not None:
        skip_mako_warning = True

    imported: set[Path] = set()
    all_definitions: list[Definition] = []
    # mutable container so nested calls can set the flag once
    mako_confirmed = [skip_mako_warning]
    _resolve_file(
        root,
        imported,
        all_definitions,
        mako_defs=mako_defs,
        mako_confirmed=mako_confirmed,
    )
    _check_no_duplicate_definition_names(all_definitions)
    return DeqFile(definitions=all_definitions, source_file=str(root))


def render_and_parse_files(
    paths: Sequence[str | Path],
    *,
    mako_defs: dict[str, str] | None = None,
    skip_mako_warning: bool = False,
) -> DeqFile:
    """Parse multiple DEQ files with shared import deduplication.

    Equivalent to creating a virtual file that ``IMPORT``s every path in
    *paths*: each real file is parsed at most once, so shared imports
    (e.g. ``code.deq``) are automatically deduplicated by the include
    guard.

    For a single file this delegates directly to
    :func:`render_and_parse_file`.
    """
    if len(paths) == 1:
        return render_and_parse_file(
            paths[0], mako_defs=mako_defs, skip_mako_warning=skip_mako_warning
        )

    import os
    import tempfile as _tempfile

    # Write a virtual file next to the first input so relative IMPORTs
    # inside the real files resolve correctly.
    first_dir = os.path.dirname(os.path.abspath(str(paths[0]))) or "."
    import_lines = (
        "\n".join(f'IMPORT "{Path(p).resolve().as_posix()}"' for p in paths) + "\n"
    )
    # Use mkstemp so the file's lifetime is fully explicit: we own both the
    # file descriptor and the path, and the file is only removed by our
    # os.unlink below. On Windows os.unlink fails on an open handle, so we
    # must close the fd before parsing/unlinking.
    fd, tmp_name = _tempfile.mkstemp(suffix=".deq", dir=first_dir, text=True)
    try:
        try:
            tf = os.fdopen(fd, "w", encoding="utf-8")
        except Exception:
            os.close(fd)
            raise
        with tf:
            tf.write(import_lines)
        result = render_and_parse_file(
            tmp_name, mako_defs=mako_defs, skip_mako_warning=skip_mako_warning
        )
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
    return result


def _resolve_file(
    file_path: Path,
    imported: set[Path],
    all_definitions: list[Definition],
    *,
    mako_defs: dict[str, str] | None = None,
    mako_confirmed: list[bool] | None = None,
) -> None:
    """Recursively parse a file and its imports.

    When *mako_defs* is not ``None`` or a file contains Mako syntax, the
    text is rendered through Mako before parsing.  The *mako_confirmed*
    flag (a mutable single-element list) ensures the user is prompted at
    most once across the entire import tree.
    """
    if file_path in imported:
        return
    imported.add(file_path)

    text = file_path.read_text(encoding="utf-8")

    # ── Mako rendering (on-the-fly) ─────────────────────────────────
    if mako_defs is not None or mako_confirmed is not None:
        from deq.circuit.mako_support import (
            confirm_mako_execution,
            has_mako_syntax,
            render_mako,
        )

        needs_render = mako_defs is not None or has_mako_syntax(text)
        if needs_render:
            if mako_confirmed is not None and not mako_confirmed[0]:
                confirm_mako_execution(str(file_path), skip_warning=False)
                mako_confirmed[0] = True
            text = render_mako(
                text, mako_defs or {}, template_dir=str(file_path.parent)
            )

    # ── Parse ────────────────────────────────────────────────────────
    try:
        deq = parse(text)
    except SyntaxError as e:
        raise SyntaxError(f"{file_path}: {e}") from e

    # Process imports first (depth-first)
    for imp in deq.imports:
        import_path = (file_path.parent / imp.path).resolve()
        if not import_path.exists():
            raise FileNotFoundError(
                f"{file_path}: imported file not found: {imp.path!r}"
            )
        _resolve_file(
            import_path,
            imported,
            all_definitions,
            mako_defs=mako_defs,
            mako_confirmed=mako_confirmed,
        )

    # Add this file's definitions with source tracking
    source = str(file_path)
    for defn in deq.definitions:
        defn.source_file = source
        all_definitions.append(defn)
