// This file is @generated by prost-build.
/// A global DEM id pair — (cid, check_index) for a detector, or
/// (eid, error_index) for an error mechanism.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DemGlobalId {
    #[prost(uint64, tag = "1")]
    pub a: u64,
    #[prost(uint64, tag = "2")]
    pub b: u64,
}
/// One Create::CheckModel: `count` new detectors (cid, 0..count) owned by
/// gadget `gid`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DemDetectorGroup {
    #[prost(uint64, tag = "1")]
    pub gid: u64,
    #[prost(uint64, tag = "2")]
    pub cid: u64,
    #[prost(uint64, tag = "3")]
    pub count: u64,
}
/// One error mechanism, fully resolved to global detector ids.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DemEdge {
    #[prost(uint64, tag = "1")]
    pub gid: u64,
    #[prost(uint64, tag = "2")]
    pub eid: u64,
    #[prost(uint64, tag = "3")]
    pub error_index: u64,
    /// global detector ids (cid, check_index) — check_bias already applied
    #[prost(message, repeated, tag = "4")]
    pub detectors: ::prost::alloc::vec::Vec<DemGlobalId>,
    #[prost(double, tag = "5")]
    pub probability: f64,
}
/// Everything that became visible since the previous DrainDem.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DemDrainResponse {
    #[prost(message, repeated, tag = "1")]
    pub detector_groups: ::prost::alloc::vec::Vec<DemDetectorGroup>,
    #[prost(message, repeated, tag = "2")]
    pub edges: ::prost::alloc::vec::Vec<DemEdge>,
}
/// One BP decode's window report, in global ids, for the decoding-graph view.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DemPrediction {
    #[prost(uint64, tag = "1")]
    pub gid: u64,
    #[prost(uint64, tag = "2")]
    pub seq: u64,
    #[prost(uint64, repeated, tag = "3")]
    pub window_gids: ::prost::alloc::vec::Vec<u64>,
    /// (eid, error_index)
    #[prost(message, repeated, tag = "4")]
    pub committed_edges: ::prost::alloc::vec::Vec<DemGlobalId>,
    #[prost(message, repeated, tag = "5")]
    pub buffer_edges: ::prost::alloc::vec::Vec<DemGlobalId>,
    #[prost(message, repeated, tag = "6")]
    pub fired: ::prost::alloc::vec::Vec<DemGlobalId>,
    #[prost(message, repeated, tag = "7")]
    pub fired_buffer: ::prost::alloc::vec::Vec<DemGlobalId>,
    /// (cid, check_index)
    #[prost(message, repeated, tag = "8")]
    pub flips: ::prost::alloc::vec::Vec<DemGlobalId>,
}
/// absent `gid` = drain all queued predictions
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DemPredictionsRequest {
    #[prost(uint64, optional, tag = "1")]
    pub gid: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DemPredictionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub predictions: ::prost::alloc::vec::Vec<DemPrediction>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DemEnabledRequest {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DetectorRequest {
    /// the gid of the gadget whose finished-detector bits to return
    #[prost(uint64, tag = "1")]
    pub gid: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnloadLibrary {
    #[prost(uint64, repeated, tag = "1")]
    pub gtype: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "2")]
    pub ctype: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "3")]
    pub etype: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResetRequest {
    /// by default keep all the library data intact; resetting this only if a
    /// completely new library is required
    #[prost(bool, tag = "1")]
    pub reset_library: bool,
    /// by default keeping all the decoder instances intact if such feature is
    /// supported; resetting the decoder service every time is useful for dynamic
    /// decoding where the decoder instances cannot be reused
    #[prost(bool, tag = "2")]
    pub reset_decoder_service: bool,
    /// other custom things
    #[prost(string, tag = "200")]
    pub custom: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteResponse {
    /// the id is either gid (gadget), cid (check model) or eid (error model)
    /// depending on the instruction
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Outcomes {
    /// the gid of the gadget
    #[prost(uint64, tag = "1")]
    pub gid: u64,
    /// the measurement outcomes, length must be equal to the number of
    /// measurements of the gadget type
    #[prost(message, optional, tag = "2")]
    pub outcomes: ::core::option::Option<super::util::BitVector>,
    /// modify the probabilities based on soft information; note that later
    /// modifications will overwrite the existing ones, so use sparse modifier as
    /// much as possible to avoid potential issues; the length of the modifier must
    /// be less than the number of error models attached to the gadget. Here we
    /// implicitly enforce that each gadget can only modify local error models,
    /// which makes sense as modifying history error model probabilities
    /// complicates the decoding system coordination (e.g., do we recompute the
    /// committed part or not?)
    #[prost(message, repeated, tag = "3")]
    pub modifiers: ::prost::alloc::vec::Vec<super::bin::ProbabilityModifier>,
    /// optional per-measurement loss flags, one bit per measurement in `outcomes`.
    /// A set bit means the corresponding qubit was lost during that measurement,
    /// and the bit in `outcomes` is therefore unreliable (typically a random
    /// substitute filled in by the simulator).  When absent, no loss information
    /// is available for this batch and the decoder should treat every measurement
    /// bit as reliable.  Decoders are free to ignore this field; no decoder is
    /// required to consume it.
    #[prost(message, optional, tag = "4")]
    pub loss_mask: ::core::option::Option<super::util::BitVector>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Readouts {
    /// the gid of the gadget
    #[prost(uint64, tag = "1")]
    pub gid: u64,
    /// the readout results; length must be equal to the number of
    /// logical readouts of the gadget type
    #[prost(message, optional, tag = "2")]
    pub readouts: ::core::option::Option<super::util::BitVector>,
    /// optionally, output logical soft information: the estimated probability
    /// of a logical readout being wrong; if provided, the length must be equal to
    /// the number of readouts in the gadget
    #[prost(double, repeated, tag = "3")]
    pub probabilities: ::prost::alloc::vec::Vec<f64>,
    /// the gadget's finished-detector parities (its check-model syndrome),
    /// populated by Decode and WaitForDetectors
    #[prost(message, optional, tag = "4")]
    pub detectors: ::core::option::Option<super::util::BitVector>,
}
/// Wall-clock timing of one window decode. All \*\_ns timestamps share the
/// process-monotonic origin of timestamp_ns(); durations are plain ns.
/// Construction phases (build/merge/compact/load) are 0 on CACHE_HIT.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WindowTiming {
    /// monotone per-shot counter, assigned by the timing log in push order
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    #[prost(uint64, repeated, tag = "2")]
    pub window_gids: ::prost::alloc::vec::Vec<u64>,
    /// max over the window's check models of their syndrome-complete time
    /// (0 when unknown, e.g. monolithic approximates with decode entry)
    #[prost(uint64, tag = "3")]
    pub syndrome_ready_ns: u64,
    #[prost(uint64, tag = "4")]
    pub decode_start_ns: u64,
    #[prost(uint64, tag = "5")]
    pub decode_end_ns: u64,
    /// window-exploration compute (select_commit_region + shrink_window); 0 monolithic
    #[prost(uint64, tag = "6")]
    pub explore_ns: u64,
    /// decoding_hypergraph()
    #[prost(uint64, tag = "7")]
    pub build_ns: u64,
    /// hyperedge merging (0 if merge_hyperedges off)
    #[prost(uint64, tag = "8")]
    pub merge_ns: u64,
    /// compact_vertices (0 monolithic)
    #[prost(uint64, tag = "9")]
    pub compact_ns: u64,
    /// load_hypergraph into the decoder service
    #[prost(uint64, tag = "10")]
    pub load_ns: u64,
    /// the decode / decode_loaded call, client-observed
    #[prost(uint64, tag = "11")]
    pub decode_ns: u64,
    #[prost(enumeration = "DecodePath", tag = "12")]
    pub path: i32,
    /// fired detectors (popcount of the syndrome)
    #[prost(uint32, tag = "13")]
    pub syndrome_weight: u32,
    /// parity_factor.subgraph.len()
    #[prost(uint32, tag = "14")]
    pub correction_weight: u32,
    #[prost(uint32, tag = "15")]
    pub num_hyperedges: u32,
    #[prost(uint32, tag = "16")]
    pub num_vertices: u32,
    /// decoder-window gadget count
    #[prost(uint32, tag = "17")]
    pub num_gadgets: u32,
    /// commit-region gadget count (== num_gadgets monolithic)
    #[prost(uint32, tag = "18")]
    pub num_committing: u32,
    /// decodes in flight when this one started (incl. self)
    #[prost(uint32, tag = "19")]
    pub concurrent_decodes: u32,
    /// loaded_decoders entries after this decode
    #[prost(uint32, tag = "20")]
    pub cache_size: u32,
    /// syndrome BitVector payload bytes
    #[prost(uint64, tag = "21")]
    pub syndrome_bytes: u64,
    /// encoded_len of the returned ParityFactor
    #[prost(uint64, tag = "22")]
    pub parity_factor_bytes: u64,
    /// encoded_len of the hypergraph at load; 0 on CACHE_HIT
    #[prost(uint64, tag = "23")]
    pub hypergraph_bytes: u64,
    /// decoder-side compute reported by the decoder service (ParityFactor.compute_ns);
    /// comms overhead = decode_ns - decoder_compute_ns
    #[prost(uint64, tag = "24")]
    pub decoder_compute_ns: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WindowTimingsResponse {
    #[prost(message, repeated, tag = "1")]
    pub timings: ::prost::alloc::vec::Vec<WindowTiming>,
}
/// How decode_parity_factor obtained its decoding hypergraph.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecodePath {
    /// reused an already-loaded hypergraph (decode_loaded, zero construction)
    CacheHit = 0,
    /// persistent decoder, first encounter: built + load_hypergraph + decode_loaded
    BuiltLoaded = 1,
    /// non-persistent config: built + inline decode (no load step)
    Temporary = 2,
}
impl DecodePath {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CacheHit => "CACHE_HIT",
            Self::BuiltLoaded => "BUILT_LOADED",
            Self::Temporary => "TEMPORARY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CACHE_HIT" => Some(Self::CacheHit),
            "BUILT_LOADED" => Some(Self::BuiltLoaded),
            "TEMPORARY" => Some(Self::Temporary),
            _ => None,
        }
    }
}
/// Generated client implementations.
#[cfg(feature = "cli")]
pub mod coordinator_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CoordinatorClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CoordinatorClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CoordinatorClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CoordinatorClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CoordinatorClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// load the library, preferably offline (well before the circuit runs) but can
        /// also run online to enable the capability of very dynamic behaviors
        pub async fn load_library(
            &mut self,
            request: impl tonic::IntoRequest<super::super::bin::Library>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/LoadLibrary",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "LoadLibrary"));
            self.inner.unary(req, path, codec).await
        }
        /// remove certain gadgets, check models or error models to free up resources
        pub async fn unload(
            &mut self,
            request: impl tonic::IntoRequest<super::UnloadLibrary>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/Unload",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "Unload"));
            self.inner.unary(req, path, codec).await
        }
        /// return the id of the new instruction (which creates an instance of a
        /// gadget, a check model or an error model)
        pub async fn execute(
            &mut self,
            request: impl tonic::IntoRequest<super::super::bin::Instruction>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/Execute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "Execute"));
            self.inner.unary(req, path, codec).await
        }
        /// input the measurement outcomes of a gadget and return the logical readouts.
        /// note that the readouts generally depend on adjacent gadgets' outcomes so
        /// it may not return immediately (unless the number of readouts are zero)
        pub async fn decode(
            &mut self,
            request: impl tonic::IntoRequest<super::Outcomes>,
        ) -> std::result::Result<tonic::Response<super::Readouts>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/Decode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "Decode"));
            self.inner.unary(req, path, codec).await
        }
        /// publish a gadget's raw measurement outcomes as soon as they exist, before
        /// its decode is requested — lets detector-conditioned control flow resolve
        /// at measurement time. decode() later re-sends the same bits idempotently.
        pub async fn submit_outcomes(
            &mut self,
            request: impl tonic::IntoRequest<super::Outcomes>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/SubmitOutcomes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("deq.coordinator.Coordinator", "SubmitOutcomes"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// return a gadget's finished-detector bits (its check-model syndrome) as soon
        /// as its checks are finished, WITHOUT waiting for the BP decode. The response
        /// populates only the `detectors` field of Readouts.
        pub async fn wait_for_detectors(
            &mut self,
            request: impl tonic::IntoRequest<super::DetectorRequest>,
        ) -> std::result::Result<tonic::Response<super::Readouts>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/WaitForDetectors",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("deq.coordinator.Coordinator", "WaitForDetectors"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// reset the system
        pub async fn reset(
            &mut self,
            request: impl tonic::IntoRequest<super::ResetRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/Reset",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "Reset"));
            self.inner.unary(req, path, codec).await
        }
        /// drain the DEM growth increments (detector groups + resolved error edges)
        /// that became visible since the previous drain — the decoding-graph view's
        /// structural data source. Recording must be enabled via SetDemEnabled.
        pub async fn drain_dem(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::DemDrainResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/DrainDem",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "DrainDem"));
            self.inner.unary(req, path, codec).await
        }
        /// drain the queued per-decode DEM predictions. An absent `gid` drains every
        /// queued prediction; a present `gid` drains only that decoded gadget's,
        /// leaving the rest queued for their owning decode.
        pub async fn drain_dem_predictions(
            &mut self,
            request: impl tonic::IntoRequest<super::DemPredictionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DemPredictionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/DrainDemPredictions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("deq.coordinator.Coordinator", "DrainDemPredictions"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// enable/disable DEM recording. The server starts with recording DISABLED;
        /// the playground turns it on per replay shot.
        pub async fn set_dem_enabled(
            &mut self,
            request: impl tonic::IntoRequest<super::DemEnabledRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/SetDemEnabled",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("deq.coordinator.Coordinator", "SetDemEnabled"));
            self.inner.unary(req, path, codec).await
        }
        /// drain the per-window decode timing records accumulated since the previous
        /// drain (or reset). Always recorded — unlike the DEM log there is no enable
        /// flag; records are ~30 scalars per window decode.
        pub async fn drain_window_timings(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::WindowTimingsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/deq.coordinator.Coordinator/DrainWindowTimings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("deq.coordinator.Coordinator", "DrainWindowTimings"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod coordinator_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CoordinatorServer.
    #[async_trait]
    pub trait Coordinator: std::marker::Send + std::marker::Sync + 'static {
        /// load the library, preferably offline (well before the circuit runs) but can
        /// also run online to enable the capability of very dynamic behaviors
        async fn load_library(
            &self,
            request: tonic::Request<super::super::bin::Library>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// remove certain gadgets, check models or error models to free up resources
        async fn unload(
            &self,
            request: tonic::Request<super::UnloadLibrary>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// return the id of the new instruction (which creates an instance of a
        /// gadget, a check model or an error model)
        async fn execute(
            &self,
            request: tonic::Request<super::super::bin::Instruction>,
        ) -> std::result::Result<tonic::Response<super::ExecuteResponse>, tonic::Status>;
        /// input the measurement outcomes of a gadget and return the logical readouts.
        /// note that the readouts generally depend on adjacent gadgets' outcomes so
        /// it may not return immediately (unless the number of readouts are zero)
        async fn decode(
            &self,
            request: tonic::Request<super::Outcomes>,
        ) -> std::result::Result<tonic::Response<super::Readouts>, tonic::Status>;
        /// publish a gadget's raw measurement outcomes as soon as they exist, before
        /// its decode is requested — lets detector-conditioned control flow resolve
        /// at measurement time. decode() later re-sends the same bits idempotently.
        async fn submit_outcomes(
            &self,
            request: tonic::Request<super::Outcomes>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// return a gadget's finished-detector bits (its check-model syndrome) as soon
        /// as its checks are finished, WITHOUT waiting for the BP decode. The response
        /// populates only the `detectors` field of Readouts.
        async fn wait_for_detectors(
            &self,
            request: tonic::Request<super::DetectorRequest>,
        ) -> std::result::Result<tonic::Response<super::Readouts>, tonic::Status>;
        /// reset the system
        async fn reset(
            &self,
            request: tonic::Request<super::ResetRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// drain the DEM growth increments (detector groups + resolved error edges)
        /// that became visible since the previous drain — the decoding-graph view's
        /// structural data source. Recording must be enabled via SetDemEnabled.
        async fn drain_dem(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<
            tonic::Response<super::DemDrainResponse>,
            tonic::Status,
        >;
        /// drain the queued per-decode DEM predictions. An absent `gid` drains every
        /// queued prediction; a present `gid` drains only that decoded gadget's,
        /// leaving the rest queued for their owning decode.
        async fn drain_dem_predictions(
            &self,
            request: tonic::Request<super::DemPredictionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DemPredictionsResponse>,
            tonic::Status,
        >;
        /// enable/disable DEM recording. The server starts with recording DISABLED;
        /// the playground turns it on per replay shot.
        async fn set_dem_enabled(
            &self,
            request: tonic::Request<super::DemEnabledRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// drain the per-window decode timing records accumulated since the previous
        /// drain (or reset). Always recorded — unlike the DEM log there is no enable
        /// flag; records are ~30 scalars per window decode.
        async fn drain_window_timings(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<
            tonic::Response<super::WindowTimingsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CoordinatorServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CoordinatorServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CoordinatorServer<T>
    where
        T: Coordinator,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/deq.coordinator.Coordinator/LoadLibrary" => {
                    #[allow(non_camel_case_types)]
                    struct LoadLibrarySvc<T: Coordinator>(pub Arc<T>);
                    impl<
                        T: Coordinator,
                    > tonic::server::UnaryService<super::super::bin::Library>
                    for LoadLibrarySvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::bin::Library>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::load_library(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoadLibrarySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/Unload" => {
                    #[allow(non_camel_case_types)]
                    struct UnloadSvc<T: Coordinator>(pub Arc<T>);
                    impl<
                        T: Coordinator,
                    > tonic::server::UnaryService<super::UnloadLibrary>
                    for UnloadSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnloadLibrary>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::unload(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnloadSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/Execute" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteSvc<T: Coordinator>(pub Arc<T>);
                    impl<
                        T: Coordinator,
                    > tonic::server::UnaryService<super::super::bin::Instruction>
                    for ExecuteSvc<T> {
                        type Response = super::ExecuteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::bin::Instruction>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::execute(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/Decode" => {
                    #[allow(non_camel_case_types)]
                    struct DecodeSvc<T: Coordinator>(pub Arc<T>);
                    impl<T: Coordinator> tonic::server::UnaryService<super::Outcomes>
                    for DecodeSvc<T> {
                        type Response = super::Readouts;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Outcomes>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::decode(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DecodeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/SubmitOutcomes" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitOutcomesSvc<T: Coordinator>(pub Arc<T>);
                    impl<T: Coordinator> tonic::server::UnaryService<super::Outcomes>
                    for SubmitOutcomesSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Outcomes>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::submit_outcomes(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubmitOutcomesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/WaitForDetectors" => {
                    #[allow(non_camel_case_types)]
                    struct WaitForDetectorsSvc<T: Coordinator>(pub Arc<T>);
                    impl<
                        T: Coordinator,
                    > tonic::server::UnaryService<super::DetectorRequest>
                    for WaitForDetectorsSvc<T> {
                        type Response = super::Readouts;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DetectorRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::wait_for_detectors(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WaitForDetectorsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/Reset" => {
                    #[allow(non_camel_case_types)]
                    struct ResetSvc<T: Coordinator>(pub Arc<T>);
                    impl<T: Coordinator> tonic::server::UnaryService<super::ResetRequest>
                    for ResetSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::reset(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/DrainDem" => {
                    #[allow(non_camel_case_types)]
                    struct DrainDemSvc<T: Coordinator>(pub Arc<T>);
                    impl<T: Coordinator> tonic::server::UnaryService<()>
                    for DrainDemSvc<T> {
                        type Response = super::DemDrainResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::drain_dem(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DrainDemSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/DrainDemPredictions" => {
                    #[allow(non_camel_case_types)]
                    struct DrainDemPredictionsSvc<T: Coordinator>(pub Arc<T>);
                    impl<
                        T: Coordinator,
                    > tonic::server::UnaryService<super::DemPredictionsRequest>
                    for DrainDemPredictionsSvc<T> {
                        type Response = super::DemPredictionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DemPredictionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::drain_dem_predictions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DrainDemPredictionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/SetDemEnabled" => {
                    #[allow(non_camel_case_types)]
                    struct SetDemEnabledSvc<T: Coordinator>(pub Arc<T>);
                    impl<
                        T: Coordinator,
                    > tonic::server::UnaryService<super::DemEnabledRequest>
                    for SetDemEnabledSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DemEnabledRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::set_dem_enabled(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetDemEnabledSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/deq.coordinator.Coordinator/DrainWindowTimings" => {
                    #[allow(non_camel_case_types)]
                    struct DrainWindowTimingsSvc<T: Coordinator>(pub Arc<T>);
                    impl<T: Coordinator> tonic::server::UnaryService<()>
                    for DrainWindowTimingsSvc<T> {
                        type Response = super::WindowTimingsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Coordinator>::drain_window_timings(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DrainWindowTimingsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CoordinatorServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "deq.coordinator.Coordinator";
    impl<T> tonic::server::NamedService for CoordinatorServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
